### ISSUE TITLE
Conflicts with django international

### ISSUE THREAD

**Issue by khashashin** [neon-jungle/wagtail-metadata#59]
wagtail-metadata worked flawlessly for me until I implemented some [Django i18n](https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#language-prefix-in-url-patterns). I'm not sure in which part of it exactly the error occurs, but if I set DEBUG to True it works correctly. If I set DEBUG to False, I get the following error:

```
Traceback (most recent call last):
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\core\handlers\base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\urls\resolvers.py", line 575, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) '^django-admin/'>], [<URLResolver <module 'wagtail.admin.urls' from 'H:\\GitHub\\leanleaders-web\\venv\\lib\\site-packages\\wagtail\\admin\\urls\\__init__.py'> (None:None) '^admin/'>], [<URLResolver <module 'wagtail.documents.urls' from 'H:\\GitHub\\leanleaders-web\\venv\\lib\\site-packages\\wagtail\\documents\\urls.py'> (None:None) '^documents/'>], [<URLPattern '^sitemap\.xml$'>], [<URLPattern '^impressum/' [name='impressum']>], [<URLPattern '^privacy-policy/' [name='privacy-policy']>], [<URLResolver <URLResolver list> (None:None) 'de/'>]], 'path': ''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\core\handlers\exception.py", line 108, in get_exception_response
    response = callback(request, **{**param_dict, 'exception': exception})
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\views\defaults.py", line 60, in page_not_found
    body = template.render(context, request)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\wagtailmetadata\templatetags\wagtailmetadata_tags.py", line 14, in meta_tags
    return tags.meta_tags(request, model)
  File "H:\GitHub\leanleaders-web\venv\lib\site-packages\wagtailmetadata\tags.py", line 20, in meta_tags
    "'meta_tags' tag is missing a model or object")
django.template.exceptions.TemplateSyntaxError: 'meta_tags' tag is missing a model or object
```
It is probably becouse of the i18n_patterns

```
urlpatterns += i18n_patterns(
        # These URLs will have /<language_code>/ appended to the beginning
	re_path(r'', include(wagtail_urls)),
)
```
This adds(redirect the page)  language code to the end of url

**Comment by seb-b** [comment]
`'meta_tags' tag is missing a model or object` is thrown when the template tag receives a null value. You can see the code here:
https://github.com/neon-jungle/wagtail-metadata/blob/master/wagtailmetadata/templatetags/wagtailmetadata_tags.py

So it looks like your url resolver is hitting a 404, and trying to display the 404 page. Usually on 404 pages you won't have a `self` in the template context and the meta tags will break while looking for it. I would recommend removing the `meta_tags` template tag from your 404 (and 500) pages, let me know if that helps

**Comment by khashashin** [comment]
Yes, I have inserted `meta_tags` in a block and used this block as empty in the templates where I do not want to use `meta_tags`:

```
<!-- Search egine metadata -->
{% block meta %}
     {% meta_tags %}
{% endblock %}
```

**Comment by seb-b** [comment]
good idea, did that fix the problem?

**Comment by khashashin** [comment]
Yeah, seems so :)
